apiVersion: v1beta3
kind: List
items:
- apiVersion: v1beta3
  kind: DeploymentConfig
  metadata:
    name: gitserver
  spec:
    triggers:
    - type: ConfigChange
    replicas: 1
    selector:
      run-container: gitserver
    template:
      metadata:
        labels:
          run-container: gitserver
      spec:
        containers:
        - name: gitserver
          image: openshift/origin-gitserver
          ports:
          - containerPort: 8080
          env:
          - name: PUBLIC_URL
            value: "http://gitserver.myproject.local:8080" # TODO: this needs to be resolved from env
          - name: GIT_HOME
            value: /var/lib/git
          - name: HOOK_PATH
            value: /var/lib/git-hooks
          - name: ALLOW_GIT_PUSH
            value: "yes"
          - name: ALLOW_GIT_HOOKS
            value: "yes"
          - name: ALLOW_LAZY_CREATE
            value: "yes"
          - name: AUTOLINK_CONFIG
            value: /var/lib/gitsecrets/admin.kubeconfig # TODO: use the service account secret
          - name: AUTOLINK_NAMESPACE
            #value: # TODO: use env generation
          - name: AUTOLINK_HOOK
            value:
          - name: REQUIRE_GIT_AUTH
            #value: user:password # if set, authentication is required to push to this server
          #- name: GIT_INITIAL_CLONE_1
          #  value:
          - name: OPENSHIFTCONFIG
            value: /var/lib/gitsecrets/admin.kubeconfig # TODO: use the service account secret
          volumeMounts:
          - name: config
            mountPath: /var/lib/gitsecrets/
            readOnly: true
        volumes:
        - name: config
          secret:
            secretName: gitserver-config
- apiVersion: v1beta3
  kind: Secret
  metadata:
    name: gitserver-config
  spec:
    data:
      # Needs to be populated
      admin.kubeconfig:
- apiVersion: v1beta3
  kind: Service
  metadata:
    name: gitserver
  spec:
    selector:
      run-container: gitserver
    ports:
    - port: 8080
      targetPort: 8080
