language: go

go:
  - 1.4

env:
 - TEST_ASSETS=true
 - TEST_ASSETS=false

install:
  - PATH=$HOME/gopath/bin:$PATH make install-travis

script:
  - make check-test TESTFLAGS="-p=4" TESTS="''" # empty quotes are because hack/test-go.sh requires 2 args

notifications:
  irc: "chat.freenode.net#openshift-dev"

sudo: false
